# -*- mode: python ; coding: utf-8 -*-


a = Analysis(
    ['main.py'],
    pathex=['src'],
    binaries=[],
    datas=[
        ('dat', 'dat'),
        ('translations.csv', '.'),
        ('src/assets/icon.ico', '.'),
        ('src', 'src'),
    ],
    hiddenimports=[
        'PyQt6.QtCore',
        'PyQt6.QtGui',
        'PyQt6.QtWidgets',
        'cryptography.fernet',
        'PIL.Image',
        'win11toast',
        'plyer',
        'asyncio',
        'core',
        'core.models',
        'core.key_manager',
        'core.alarm_service',
        'gui',
        'gui.widgets',
        'gui.image_viewer_window',
        'utils',
        'utils.helpers',
        'utils.language_manager',
        'utils.log_manager',
        'utils.qt_resource_loader',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=['matplotlib', 'numpy', 'pandas', 'scipy', 'IPython', 'jupyter', 'tkinter'],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='Croquis',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='src/assets/icon.ico',
)
